# Site
name: "Future proof"
title: "Future proof"
description: "Writings on innovation, tech, and policy."
logo: 'assets/images/FP.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'G-DZZ2HC3NY8'
disqus: 'edwardpaulino-com'
mailchimp-list: 'https://edwardpaulino.us17.list-manage.com/subscribe/post?u=e1393cf5a631e6fe336c7d335'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ed:
    name: Ed
    display_name: Edward Paulino
    gravatar: 65d9907bf5fd9775e6be5bdccaa399e4
    email: edpaulinojr@gmail.com
    web: https://edwardpaulino.com/about
    twitter: https://twitter.com/edpaulinojr
    description: "In a world with plenty of challenges, Ed likes to research, advocate, and test solutions to problems that matter."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
